version: '3.7'

services:
  redis:
    image: redis:5.0.5
    container_name: marvel_redis
    ports:
      - "6379:6379"
  marvel_docker:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - redis
    networks:
      - default
    ports:
      - "9091:9091"